select * from ADDRESS;
select count(*) from ADDRESS;

select * from USERID;
select count(*) from USERID;

select * from USERSESSION;
select count(*) from USERSESSION;

select * from URISTEAM1;
select * 
  from URISTEAM 
  where FILE like '/hlace%';

select * from USERSESSION_PAGEVIEWABS;

select * from PAGEVIEW;

select USERSESSION.ID, ADDRESS.ADDRESS as IP, URISTEAM.FILE, URIQUERYPAIR.VALUE as QUERYVALUE, URIQUERYKEY.NAME as QUERYKEY, REQUEST.DATE, REQUEST.TIME, REQUEST.SIZE_OF_RESPONSE, PROTOCOL.PROTOCOL, PROTOCOL.VERSION, REQUEST.STATUS_CODE
  from USERID 
  join ADDRESS on USERID.ADDRESS_ID = ADDRESS.id
  join USERSESSION on USERID.ID = USERSESSION.USERID_ID
  join USERSESSION_PAGEVIEWABS on USERSESSION.ID = USERSESSION_PAGEVIEWABS.USERSESSION_ID
  join PAGEVIEW on USERSESSION_PAGEVIEWABS.PAGES_ID = PAGEVIEW.ID
  join PAGEVIEWABS_REQUESTABS on PAGEVIEW.ID = PAGEVIEWABS_REQUESTABS.PAGEVIEWABS_ID
  join REQUEST on PAGEVIEWABS_REQUESTABS.REQUESTS_ID = REQUEST.ID
  join REQUESTLINE on REQUEST.REQUESTLINE_ID = REQUESTLINE.ID
  join PROTOCOL on REQUESTLINE.PROTOCOL_ID = PROTOCOL.ID
  join URISTEAMQUERY on REQUESTLINE.STEAMQUERY_ID = URISTEAMQUERY.ID
  join URISTEAM on URISTEAMQUERY.URISTEAM_ID = URISTEAM.ID
  join URIQUERY on URISTEAMQUERY.QUERY_ID = URIQUERY.ID
  join URIQUERY_URIQUERYPAIR on URIQUERY.ID = URIQUERY_URIQUERYPAIR.URIQUERY_ID
  join URIQUERYPAIR on URIQUERY_URIQUERYPAIR.PAIRS_ID = URIQUERYPAIR.ID
  join URIQUERYKEY on URIQUERYPAIR.KEY_ID = URIQUERYKEY.ID
  where ADDRESS.ADDRESS like '157.55.39.19'
  order by REQUEST.DATE asc, REQUEST.TIME asc;
